In [12]:
import pandas as pd

In [13]:
import sys
from pathlib import Path

# Find project root (RetailPulse)
PROJECT_ROOT = Path.cwd().parent

# Add project root to Python path
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

import pandas as pd

from src.etl.ingest import load_data

from src.forecasting.preprocessing import *

from src.forecasting.prophet_model import *

from src.forecasting.evaluation import *

from src.forecasting.visualization import *

In [14]:
import os
print(os.getcwd())

c:\Users\Windows 10 Pro\OneDrive\Desktop\RETAILPULSE\notebooks

In [15]:
print(PROJECT_ROOT)

c:\Users\Windows 10 Pro\OneDrive\Desktop\RETAILPULSE

In [16]:
df = load_data("../data/processed/online_retail_processed.csv")
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,is_cancelled,TotalPrice,Year,Month,Day,DayOfWeek,Hour,Quarter,IsWeekend,InvoiceMonth
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,False,83.4,2009,12,1,Tuesday,7,4,False,2009-12
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,False,81.0,2009,12,1,Tuesday,7,4,False,2009-12
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,False,81.0,2009,12,1,Tuesday,7,4,False,2009-12
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,False,100.8,2009,12,1,Tuesday,7,4,False,2009-12
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,False,30.0,2009,12,1,Tuesday,7,4,False,2009-12

In [17]:
monthly_sales = prepare_monthly_sales(df)

monthly_sales.head()

        Date       Sales
0 2009-12-31  796648.500
1 2010-01-31  622479.502
2 2010-02-28  531265.366
3 2010-03-31  763247.241
4 2010-04-30  641521.052

In [18]:
monthly_sales.tail()

         Date        Sales
20 2011-08-31   703510.580
21 2011-09-30  1017596.682
22 2011-10-31  1069368.230
23 2011-11-30  1456145.800
24 2011-12-31   432719.060

In [19]:
monthly_sales.shape

(25, 2)

prophet_df = prepare_prophet_data(
    monthly_sales
)

prophet_df.head()

In [20]:
prophet_df = prepare_prophet_data(
    monthly_sales
)

prophet_df.head()

          ds           y
0 2009-12-31  796648.500
1 2010-01-31  622479.502
2 2010-02-28  531265.366
3 2010-03-31  763247.241
4 2010-04-30  641521.052

In [21]:
model = train_prophet(
    prophet_df
)

21:02:49 - cmdstanpy - INFO - Chain [1] start processing
21:02:50 - cmdstanpy - INFO - Chain [1] done processing

In [22]:
forecast = forecast_sales(
    model,
    periods=12
)

In [23]:
forecast.head()

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,additive_terms,additive_terms_lower,additive_terms_upper,yearly,yearly_lower,yearly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat
0,2009-12-31,752254.210490,775723.462013,882172.535336,752254.210490,752254.210490,75265.965445,75265.965445,75265.965445,75265.965445,75265.965445,75265.965445,0.0,0.0,0.0,827520.175935
1,2010-01-31,751412.842402,525428.872008,626094.750166,751412.842402,751412.842402,-177711.813803,-177711.813803,-177711.813803,-177711.813803,-177711.813803,-177711.813803,0.0,0.0,0.0,573701.028599
2,2010-02-28,750652.897042,432190.908493,525928.940408,750652.897042,750652.897042,-272388.410589,-272388.410589,-272388.410589,-272388.410589,-272388.410589,-272388.410589,0.0,0.0,0.0,478264.486453
3,2010-03-31,749811.528871,674091.752422,776614.577863,749811.528871,749811.528871,-22905.680807,-22905.680807,-22905.680807,-22905.680807,-22905.680807,-22905.680807,0.0,0.0,0.0,726905.848064
4,2010-04-30,748997.301656,576117.414955,677819.307942,748997.301656,748997.301656,-122073.274873,-122073.274873,-122073.274873,-122073.274873,-122073.274873,-122073.274873,0.0,0.0,0.0,626924.026783

In [24]:
forecast.tail()

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,additive_terms,additive_terms_lower,additive_terms_upper,yearly,yearly_lower,yearly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat
32,2012-08-31,730373.024532,7.126890e+05,8.104917e+05,730154.149213,730576.426139,31613.244663,31613.244663,31613.244663,31613.244663,31613.244663,31613.244663,0.0,0.0,0.0,7.619863e+05
33,2012-09-30,729752.407072,6.232673e+05,7.251363e+05,729483.044421,729999.367932,-54480.848806,-54480.848806,-54480.848806,-54480.848806,-54480.848806,-54480.848806,0.0,0.0,0.0,6.752716e+05
34,2012-10-31,729111.102362,1.108285e+06,1.212676e+06,728801.220036,729409.656971,431044.347576,431044.347576,431044.347576,431044.347576,431044.347576,431044.347576,0.0,0.0,0.0,1.160155e+06
35,2012-11-30,728490.484902,1.230766e+06,1.326349e+06,728130.230244,728840.653568,546452.944708,546452.944708,546452.944708,546452.944708,546452.944708,546452.944708,0.0,0.0,0.0,1.274943e+06
36,2012-12-31,727849.180193,9.151815e+05,1.014008e+06,727439.784774,728246.072977,235767.354619,235767.354619,235767.354619,235767.354619,235767.354619,235767.354619,0.0,0.0,0.0,9.636165e+05

In [25]:
forecast_plot(
    forecast
).show()

In [26]:
forecast[
    ["ds","yhat"]
].tail(12)

           ds          yhat
25 2012-01-31  6.449872e+05
26 2012-02-29  2.983277e+05
27 2012-03-31  7.023384e+05
28 2012-04-30  8.355483e+05
29 2012-05-31  4.183459e+05
30 2012-06-30  7.703967e+05
31 2012-07-31  6.726332e+05
32 2012-08-31  7.619863e+05
33 2012-09-30  6.752716e+05
34 2012-10-31  1.160155e+06
35 2012-11-30  1.274943e+06
36 2012-12-31  9.636165e+05

In [27]:
from pathlib import Path

PROJECT_ROOT = Path.cwd()

while PROJECT_ROOT.name != "RETAILPULSE":
    PROJECT_ROOT = PROJECT_ROOT.parent

output_dir = PROJECT_ROOT / "data" / "processed"
output_dir.mkdir(parents=True, exist_ok=True)

forecast.to_csv(
    output_dir / "sales_forecast.csv",
    index=False
)

print("Forecast Saved Successfully!")

Forecast Saved Successfully!

In [28]:
import tensorflow as tf

print(tf.__version__)

2.21.0

In [29]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

print("TensorFlow is working!")

TensorFlow is working!

In [30]:
from src.forecasting.lstm_model import *

import numpy as np
import pandas as pd

In [32]:
from importlib import reload
import src.forecasting.preprocessing as preprocessing

reload(preprocessing)

from src.forecasting.preprocessing import *

In [33]:
scaled_data, scaler = prepare_lstm_data(monthly_sales)

print(scaled_data.shape)

(25, 1)

In [34]:
X, y = create_sequences(
    scaled_data,
    sequence_length=12
)

print("X Shape:", X.shape)
print("y Shape:", y.shape)

X Shape: (13, 12, 1)
y Shape: (13, 1)

In [35]:
model = build_lstm_model(
    (X.shape[1], X.shape[2])
)

model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

c:\Users\Windows 10 Pro\OneDrive\Desktop\RETAILPULSE\venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 64)             │        16,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 19,009 (74.25 KB)

 Trainable params: 19,009 (74.25 KB)

 Non-trainable params: 0 (0.00 B)

In [36]:
history = train_lstm(
    model,
    X,
    y,
    epochs=100,
    batch_size=4
)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 4s 19ms/step - loss: 0.1784
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.1515
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.1339
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.1211
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.1081
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0963
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0840
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0758
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.0738
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.0719
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.0724
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0726
Epoch 13/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0718
Epoch 14/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0726
Epoch 15/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0732
Epoch 16/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0719
Epoch 17/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0711
Epoch 18/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0715
Epoch 19/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0718
Epoch 20/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0724
Epoch 21/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0727
Epoch 22/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0721
Epoch 23/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0705
Epoch 24/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0705
Epoch 25/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0722
Epoch 26/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0728
Epoch 27/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0716
Epoch 28/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0703
Epoch 29/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0695
Epoch 30/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0692
Epoch 31/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0700
Epoch 32/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0696
Epoch 33/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0700
Epoch 34/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0698
Epoch 35/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0687
Epoch 36/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0679
Epoch 37/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0676
Epoch 38/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0670
Epoch 39/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0657
Epoch 40/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0643
Epoch 41/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0629
Epoch 42/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0616
Epoch 43/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0603
Epoch 44/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0597
Epoch 45/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0588
Epoch 46/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0564
Epoch 47/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0543
Epoch 48/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0542
Epoch 49/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0503
Epoch 50/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0505
Epoch 51/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0448
Epoch 52/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0427
Epoch 53/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0406
Epoch 54/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0397
Epoch 55/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0399
Epoch 56/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0345
Epoch 57/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0360
Epoch 58/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0361
Epoch 59/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0280
Epoch 60/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0314
Epoch 61/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0290
Epoch 62/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0493
Epoch 63/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0513
Epoch 64/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0348
Epoch 65/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.0259
Epoch 66/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0326
Epoch 67/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0285
Epoch 68/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0303
Epoch 69/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0277
Epoch 70/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0240
Epoch 71/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0235
Epoch 72/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0234
Epoch 73/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0220
Epoch 74/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0201
Epoch 75/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0196
Epoch 76/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0194
Epoch 77/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0201
Epoch 78/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0208
Epoch 79/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0197
Epoch 80/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0223
Epoch 81/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0203
Epoch 82/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0186
Epoch 83/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0224
Epoch 84/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0194
Epoch 85/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0163
Epoch 86/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0189
Epoch 87/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0130
Epoch 88/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0300
Epoch 89/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0187
Epoch 90/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0218
Epoch 91/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0131
Epoch 92/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0197
Epoch 93/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0160
Epoch 94/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0130
Epoch 95/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0295
Epoch 96/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0082
Epoch 97/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0193
Epoch 98/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0218
Epoch 99/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0113
Epoch 100/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0150

In [37]:
predictions = predict_lstm(
    model,
    X
)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 318ms/step

In [38]:
predicted_sales = scaler.inverse_transform(predictions)

actual_sales = scaler.inverse_transform(y)

predicted_sales[:5]

array([[669015.44],
       [608013.06],
       [610010.9 ],
       [629851.7 ],
       [620879.4 ]], dtype=float32)

In [39]:
comparison = pd.DataFrame({
    "Actual": actual_sales.flatten(),
    "Predicted": predicted_sales.flatten()
})

comparison.head()

       Actual    Predicted
0  746723.610  669015.4375
1  558448.560  608013.0625
2  497026.410  610010.8750
3  682013.980  629851.6875
4  492367.841  620879.3750

In [40]:
metrics = evaluate(
    comparison["Actual"],
    comparison["Predicted"]
)

metrics

{'MAE': 94491.86,
 'RMSE': np.float64(113294.9),
 'MAPE': np.float64(14.67),
 'R2': 0.83}

In [41]:
import plotly.express as px

fig = px.line(
    comparison,
    title="LSTM: Actual vs Predicted Sales"
)

fig.show()

In [42]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

output_dir = PROJECT_ROOT / "data" / "processed"
output_dir.mkdir(parents=True, exist_ok=True)

comparison.to_csv(
    output_dir / "lstm_forecast.csv",
    index=False
)

print("LSTM Forecast Saved Successfully!")

LSTM Forecast Saved Successfully!